mysqldb:
    type: mysql:10.0
    disk: 512
    configuration:
        schemas:
            - main
        endpoints:
            mysql:
                default_schema: main
                privileges:
                    main: admin

rediscache:
    type: 'redis:3.2'

redissession:
    type: redis-persistent:3.2
    disk: 1024
