FROM php:7.3-fpm
LABEL com.contextualcode.platformcc=""

COPY conf/nginx.conf /usr/local/nginx/conf/nginx.conf
COPY conf/fastcgi_params /usr/local/nginx/conf/fastcgi_params
COPY conf/*.sh /opt/

RUN PHP_VER=7 /opt/install_dependencies.sh && \
    PHP_VER=7 /opt/config_php.sh && \
    PHP_VER=7 /opt/build_ext.sh
