#!/usr/bin/env bash

python2 -m virtualenv ./env
./env/bin/python -m pip install -r requirements.txt
echo ""
echo "###################################################"
echo "Enter Virtualenv with: 'source env/bin/activate'!!"
echo "###################################################"
echo ""
