#!/usr/bin/env bash

python2 -m virtualenv .
./bin/python -m pip install -r requirements.txt
echo ""
echo "###################################################"
echo "Enter Virtualenv with: 'source bin/activate'!!"
echo "###################################################"
echo ""