#!/usr/bin/env bash

python3 -m virtualenv ./env
./env/bin/python3 -m pip install -r requirements.txt
echo ""
echo "###################################################"
echo "Enter Virtualenv with: 'source env/bin/activate'!!"
echo "###################################################"
echo ""
