.backend: &backend
    type: upstream
    upstream: test_app:http
    cache:
        enabled: false
    ssi:
        enabled: true
    redirects:
        paths:
            /test:
                to: /test2
            ^/test3/(.*)$:
                to: "/test4/$1"
                regexp: true

https://www.contextualcode.com/: *backend
http://www.contextualcode.com/: *backend
https://cdn-backend.contextualcode.ccplatform.net/: *backend
http://health.contextualcode.ccplatform.net/: *backend

https://contextualcode.com/:
    type: redirect
    to: https://www.contextualcode.com/

https://test.contextualcode.com/test/:
    type: redirect
    to: https://www.contextualcode.com/