mysqldb:
    type: mysql:10.0
    disk: 512
    configuration:
        schemas:
            - main
        endpoints:
            mysql:
                default_schema: main
                privileges:
                    main: admin

redis-cache:
    type: 'redis:3.2'

redis-session:
    type: redis-persistent:3.2
    disk: 1024

solr-search:
    type: solr:6.6
    disk: 4096
    size: L
    configuration:
        cores:
            test:
                conf_dir: !archive "solr/test"
        endpoints:
            test:
                core: test
