provision:
    -
        desc: "Create 'web' user."
        cmd: |
            useradd -d /app -m -p 'secret~' web
            
    -
        desc: "Create self signed SSL certificate."
        cmd: |
            apt-get update
            apt-get install openssl
            apt-get clean
            mkdir /etc/nginx/ssl
            cd /etc/nginx/ssl
            openssl genrsa -des3 -passout "pass:^nx/{Dm[[k3b]ATf" -out server.pass.key 2048
            openssl rsa -passin "pass:^nx/{Dm[[k3b]ATf" -in server.pass.key -out server.key
            rm server.pass.key
            openssl req -new -key server.key -out server.csr \
                -subj "/C=US/ST=Florida/L=Tallahassee/O=ContextualCode/OU=Developers/CN=dev.local"
            openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

web_conf: |
    user web;
    worker_processes 1;
    events {
        worker_connections  1024;
    }
    http {
        include mime.types;
        default_type application/octet-stream;
        sendfile on;
        keepalive_timeout 65;
        server {
            listen 80;
            server_name localhost;
            {{APP_WEB}}
        }
    }

router_conf: |
    user web;
    worker_processes 1;
    events {
        worker_connections  1024;
    }
    http {
        include mime.types;
        default_type application/octet-stream;
        sendfile on;
        keepalive_timeout 65;
        include /router/*.conf;
    }